/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SelectWorkspaceRouteImport } from './routes/select-workspace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedUsersRouteImport } from './routes/_authed/users'
import { Route as AuthedUomRouteImport } from './routes/_authed/uom'
import { Route as AuthedSuppliersRouteImport } from './routes/_authed/suppliers'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedSerialsRouteImport } from './routes/_authed/serials'
import { Route as AuthedRolesRouteImport } from './routes/_authed/roles'
import { Route as AuthedReceivingsRouteImport } from './routes/_authed/receivings'
import { Route as AuthedProductsRouteImport } from './routes/_authed/products'
import { Route as AuthedPermissionsRouteImport } from './routes/_authed/permissions'
import { Route as AuthedMovementsRouteImport } from './routes/_authed/movements'
import { Route as AuthedInventoryRouteImport } from './routes/_authed/inventory'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedCompaniesRouteImport } from './routes/_authed/companies'
import { Route as AuthedCategoriesRouteImport } from './routes/_authed/categories'
import { Route as AuthedBatchesRouteImport } from './routes/_authed/batches'
import { Route as AuthedAdjustmentsRouteImport } from './routes/_authed/adjustments'
import { Route as AuthedPurchaseOrdersIndexRouteImport } from './routes/_authed/purchase-orders/index'
import { Route as AuthedLocationsIndexRouteImport } from './routes/_authed/locations/index'
import { Route as AuthedPurchaseOrdersIdRouteImport } from './routes/_authed/purchase-orders/$id'
import { Route as AuthedLocationsIdRouteImport } from './routes/_authed/locations/$id'

const SelectWorkspaceRoute = SelectWorkspaceRouteImport.update({
  id: '/select-workspace',
  path: '/select-workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedUsersRoute = AuthedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedUomRoute = AuthedUomRouteImport.update({
  id: '/uom',
  path: '/uom',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSuppliersRoute = AuthedSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSerialsRoute = AuthedSerialsRouteImport.update({
  id: '/serials',
  path: '/serials',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRolesRoute = AuthedRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedReceivingsRoute = AuthedReceivingsRouteImport.update({
  id: '/receivings',
  path: '/receivings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProductsRoute = AuthedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPermissionsRoute = AuthedPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMovementsRoute = AuthedMovementsRouteImport.update({
  id: '/movements',
  path: '/movements',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedInventoryRoute = AuthedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCompaniesRoute = AuthedCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCategoriesRoute = AuthedCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBatchesRoute = AuthedBatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdjustmentsRoute = AuthedAdjustmentsRouteImport.update({
  id: '/adjustments',
  path: '/adjustments',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPurchaseOrdersIndexRoute =
  AuthedPurchaseOrdersIndexRouteImport.update({
    id: '/purchase-orders/',
    path: '/purchase-orders/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedLocationsIndexRoute = AuthedLocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPurchaseOrdersIdRoute = AuthedPurchaseOrdersIdRouteImport.update({
  id: '/purchase-orders/$id',
  path: '/purchase-orders/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedLocationsIdRoute = AuthedLocationsIdRouteImport.update({
  id: '/locations/$id',
  path: '/locations/$id',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/select-workspace': typeof SelectWorkspaceRoute
  '/adjustments': typeof AuthedAdjustmentsRoute
  '/batches': typeof AuthedBatchesRoute
  '/categories': typeof AuthedCategoriesRoute
  '/companies': typeof AuthedCompaniesRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/inventory': typeof AuthedInventoryRoute
  '/movements': typeof AuthedMovementsRoute
  '/permissions': typeof AuthedPermissionsRoute
  '/products': typeof AuthedProductsRoute
  '/receivings': typeof AuthedReceivingsRoute
  '/roles': typeof AuthedRolesRoute
  '/serials': typeof AuthedSerialsRoute
  '/settings': typeof AuthedSettingsRoute
  '/suppliers': typeof AuthedSuppliersRoute
  '/uom': typeof AuthedUomRoute
  '/users': typeof AuthedUsersRoute
  '/locations/$id': typeof AuthedLocationsIdRoute
  '/purchase-orders/$id': typeof AuthedPurchaseOrdersIdRoute
  '/locations/': typeof AuthedLocationsIndexRoute
  '/purchase-orders/': typeof AuthedPurchaseOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/select-workspace': typeof SelectWorkspaceRoute
  '/adjustments': typeof AuthedAdjustmentsRoute
  '/batches': typeof AuthedBatchesRoute
  '/categories': typeof AuthedCategoriesRoute
  '/companies': typeof AuthedCompaniesRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/inventory': typeof AuthedInventoryRoute
  '/movements': typeof AuthedMovementsRoute
  '/permissions': typeof AuthedPermissionsRoute
  '/products': typeof AuthedProductsRoute
  '/receivings': typeof AuthedReceivingsRoute
  '/roles': typeof AuthedRolesRoute
  '/serials': typeof AuthedSerialsRoute
  '/settings': typeof AuthedSettingsRoute
  '/suppliers': typeof AuthedSuppliersRoute
  '/uom': typeof AuthedUomRoute
  '/users': typeof AuthedUsersRoute
  '/locations/$id': typeof AuthedLocationsIdRoute
  '/purchase-orders/$id': typeof AuthedPurchaseOrdersIdRoute
  '/locations': typeof AuthedLocationsIndexRoute
  '/purchase-orders': typeof AuthedPurchaseOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/select-workspace': typeof SelectWorkspaceRoute
  '/_authed/adjustments': typeof AuthedAdjustmentsRoute
  '/_authed/batches': typeof AuthedBatchesRoute
  '/_authed/categories': typeof AuthedCategoriesRoute
  '/_authed/companies': typeof AuthedCompaniesRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/inventory': typeof AuthedInventoryRoute
  '/_authed/movements': typeof AuthedMovementsRoute
  '/_authed/permissions': typeof AuthedPermissionsRoute
  '/_authed/products': typeof AuthedProductsRoute
  '/_authed/receivings': typeof AuthedReceivingsRoute
  '/_authed/roles': typeof AuthedRolesRoute
  '/_authed/serials': typeof AuthedSerialsRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/suppliers': typeof AuthedSuppliersRoute
  '/_authed/uom': typeof AuthedUomRoute
  '/_authed/users': typeof AuthedUsersRoute
  '/_authed/locations/$id': typeof AuthedLocationsIdRoute
  '/_authed/purchase-orders/$id': typeof AuthedPurchaseOrdersIdRoute
  '/_authed/locations/': typeof AuthedLocationsIndexRoute
  '/_authed/purchase-orders/': typeof AuthedPurchaseOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/select-workspace'
    | '/adjustments'
    | '/batches'
    | '/categories'
    | '/companies'
    | '/dashboard'
    | '/inventory'
    | '/movements'
    | '/permissions'
    | '/products'
    | '/receivings'
    | '/roles'
    | '/serials'
    | '/settings'
    | '/suppliers'
    | '/uom'
    | '/users'
    | '/locations/$id'
    | '/purchase-orders/$id'
    | '/locations/'
    | '/purchase-orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/select-workspace'
    | '/adjustments'
    | '/batches'
    | '/categories'
    | '/companies'
    | '/dashboard'
    | '/inventory'
    | '/movements'
    | '/permissions'
    | '/products'
    | '/receivings'
    | '/roles'
    | '/serials'
    | '/settings'
    | '/suppliers'
    | '/uom'
    | '/users'
    | '/locations/$id'
    | '/purchase-orders/$id'
    | '/locations'
    | '/purchase-orders'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/select-workspace'
    | '/_authed/adjustments'
    | '/_authed/batches'
    | '/_authed/categories'
    | '/_authed/companies'
    | '/_authed/dashboard'
    | '/_authed/inventory'
    | '/_authed/movements'
    | '/_authed/permissions'
    | '/_authed/products'
    | '/_authed/receivings'
    | '/_authed/roles'
    | '/_authed/serials'
    | '/_authed/settings'
    | '/_authed/suppliers'
    | '/_authed/uom'
    | '/_authed/users'
    | '/_authed/locations/$id'
    | '/_authed/purchase-orders/$id'
    | '/_authed/locations/'
    | '/_authed/purchase-orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SelectWorkspaceRoute: typeof SelectWorkspaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/select-workspace': {
      id: '/select-workspace'
      path: '/select-workspace'
      fullPath: '/select-workspace'
      preLoaderRoute: typeof SelectWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/users': {
      id: '/_authed/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthedUsersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/uom': {
      id: '/_authed/uom'
      path: '/uom'
      fullPath: '/uom'
      preLoaderRoute: typeof AuthedUomRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/suppliers': {
      id: '/_authed/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AuthedSuppliersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/serials': {
      id: '/_authed/serials'
      path: '/serials'
      fullPath: '/serials'
      preLoaderRoute: typeof AuthedSerialsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/roles': {
      id: '/_authed/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthedRolesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/receivings': {
      id: '/_authed/receivings'
      path: '/receivings'
      fullPath: '/receivings'
      preLoaderRoute: typeof AuthedReceivingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/products': {
      id: '/_authed/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthedProductsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/permissions': {
      id: '/_authed/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof AuthedPermissionsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/movements': {
      id: '/_authed/movements'
      path: '/movements'
      fullPath: '/movements'
      preLoaderRoute: typeof AuthedMovementsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/inventory': {
      id: '/_authed/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthedInventoryRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/companies': {
      id: '/_authed/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AuthedCompaniesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/categories': {
      id: '/_authed/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AuthedCategoriesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/batches': {
      id: '/_authed/batches'
      path: '/batches'
      fullPath: '/batches'
      preLoaderRoute: typeof AuthedBatchesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/adjustments': {
      id: '/_authed/adjustments'
      path: '/adjustments'
      fullPath: '/adjustments'
      preLoaderRoute: typeof AuthedAdjustmentsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/purchase-orders/': {
      id: '/_authed/purchase-orders/'
      path: '/purchase-orders'
      fullPath: '/purchase-orders/'
      preLoaderRoute: typeof AuthedPurchaseOrdersIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/locations/': {
      id: '/_authed/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof AuthedLocationsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/purchase-orders/$id': {
      id: '/_authed/purchase-orders/$id'
      path: '/purchase-orders/$id'
      fullPath: '/purchase-orders/$id'
      preLoaderRoute: typeof AuthedPurchaseOrdersIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/locations/$id': {
      id: '/_authed/locations/$id'
      path: '/locations/$id'
      fullPath: '/locations/$id'
      preLoaderRoute: typeof AuthedLocationsIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAdjustmentsRoute: typeof AuthedAdjustmentsRoute
  AuthedBatchesRoute: typeof AuthedBatchesRoute
  AuthedCategoriesRoute: typeof AuthedCategoriesRoute
  AuthedCompaniesRoute: typeof AuthedCompaniesRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedInventoryRoute: typeof AuthedInventoryRoute
  AuthedMovementsRoute: typeof AuthedMovementsRoute
  AuthedPermissionsRoute: typeof AuthedPermissionsRoute
  AuthedProductsRoute: typeof AuthedProductsRoute
  AuthedReceivingsRoute: typeof AuthedReceivingsRoute
  AuthedRolesRoute: typeof AuthedRolesRoute
  AuthedSerialsRoute: typeof AuthedSerialsRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedSuppliersRoute: typeof AuthedSuppliersRoute
  AuthedUomRoute: typeof AuthedUomRoute
  AuthedUsersRoute: typeof AuthedUsersRoute
  AuthedLocationsIdRoute: typeof AuthedLocationsIdRoute
  AuthedPurchaseOrdersIdRoute: typeof AuthedPurchaseOrdersIdRoute
  AuthedLocationsIndexRoute: typeof AuthedLocationsIndexRoute
  AuthedPurchaseOrdersIndexRoute: typeof AuthedPurchaseOrdersIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdjustmentsRoute: AuthedAdjustmentsRoute,
  AuthedBatchesRoute: AuthedBatchesRoute,
  AuthedCategoriesRoute: AuthedCategoriesRoute,
  AuthedCompaniesRoute: AuthedCompaniesRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedInventoryRoute: AuthedInventoryRoute,
  AuthedMovementsRoute: AuthedMovementsRoute,
  AuthedPermissionsRoute: AuthedPermissionsRoute,
  AuthedProductsRoute: AuthedProductsRoute,
  AuthedReceivingsRoute: AuthedReceivingsRoute,
  AuthedRolesRoute: AuthedRolesRoute,
  AuthedSerialsRoute: AuthedSerialsRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedSuppliersRoute: AuthedSuppliersRoute,
  AuthedUomRoute: AuthedUomRoute,
  AuthedUsersRoute: AuthedUsersRoute,
  AuthedLocationsIdRoute: AuthedLocationsIdRoute,
  AuthedPurchaseOrdersIdRoute: AuthedPurchaseOrdersIdRoute,
  AuthedLocationsIndexRoute: AuthedLocationsIndexRoute,
  AuthedPurchaseOrdersIndexRoute: AuthedPurchaseOrdersIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  SelectWorkspaceRoute: SelectWorkspaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
